#!/bin/bash
set -e -u -o pipefail
[[ "$GITHUB_REF" != refs/tags/* ]] && echo "${GITHUB_REF} is not a tag, exiting..." && exit 78
[ -f "$GHR_PATH" ] && cd -- "$(dirname -- "$GHR_PATH")" && export GHR_PATH="$(basename -- "$GHR_PATH")"
[ -d "$GHR_PATH" ] && cd -- "$GHR_PATH" && export GHR_PATH=.
[ -n "${GHR_COMPRESS:-}" ] && eval "$(/usr/local/bin/ghr-compress)"
export FLAGS=""
[ -n "${GHR_DRAFT}" ] && export FLAGS="$FLAGS -draft"
[ -n "${GHR_PRERELEASE}" ] && export FLAGS="$FLAGS -prerelease"
[ -n "${GHR_SOFT}" ] && export FLAGS="$FLAGS -soft"
[ -n "${GHR_DELETE}" ] && export FLAGS="$FLAGS -delete"
[ -n "${GHR_REPLACE}" ] && export FLAGS="$FLAGS -replace"

/usr/local/bin/ghr -u "${GITHUB_REPOSITORY%/*}" -r "${GITHUB_REPOSITORY#*/}" ${FLAGS} "${GITHUB_REF#refs/tags/}" "$GHR_PATH"
